BEGIN TRANSACTION;
INSERT INTO "INGRD_USE" VALUES (4,8,1.0);
INSERT INTO "INGRD_USE" VALUES (4,5,10.0);
INSERT INTO "INGRD_USE" VALUES (4,1,10.0);
INSERT INTO "INGRD_USE" VALUES (3,1,10.0);
INSERT INTO "INGRD_USE" VALUES (3,2,5.0);
INSERT INTO "INGRD_USE" VALUES (3,3,10.0);
INSERT INTO "INGRD_USE" VALUES (3,4,10.0);
INSERT INTO "INGRD_USE" VALUES (3,7,1.0);
INSERT INTO "INGRD_USE" VALUES (1,1,10.0);
INSERT INTO "INGRD_USE" VALUES (1,2,5.0);
INSERT INTO "INGRD_USE" VALUES (1,3,5.0);
INSERT INTO "INGRD_USE" VALUES (1,9,1.0);
INSERT INTO "INGRD_USE" VALUES (1,10,2.0);
INSERT INTO "INGRD_USE" VALUES (1,14,5.0);
INSERT INTO "INGRD_USE" VALUES (2,1,10.0);
INSERT INTO "INGRD_USE" VALUES (2,2,5.0);
INSERT INTO "INGRD_USE" VALUES (2,3,5.0);
INSERT INTO "INGRD_USE" VALUES (2,9,1.0);
INSERT INTO "INGRD_USE" VALUES (2,10,2.0);
INSERT INTO "INGRD_USE" VALUES (2,14,5.0);
INSERT INTO "INGRD_USE" VALUES (18,15,1.0);
INSERT INTO "INGRD_USE" VALUES (99,16,1.0);
INSERT INTO "INGRD_USE" VALUES (100,17,1.0);
INSERT INTO "INGRD_USE" VALUES (101,18,1.0);
INSERT INTO "INGRD_USE" VALUES (102,19,1.0);
INSERT INTO "INGRD_USE" VALUES (3,10,2.0);
INSERT INTO "INGRD_USE" VALUES (4,10,2.0);
INSERT INTO "MENU_OPT" VALUES (2,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (2,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (2,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (1,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (5,'치킨팩_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (5,'치킨팩_소스',2,2);
INSERT INTO "MENU_OPT" VALUES (5,'추가구매제품',0,1);
INSERT INTO "MENU_OPT" VALUES (6,'치킨팩_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (6,'치킨팩_소스',1,1);
INSERT INTO "MENU_OPT" VALUES (6,'추가구매제품',0,1);
INSERT INTO "MENU_OPT" VALUES (3,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (4,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (19,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (21,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (22,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (25,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (26,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (27,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (30,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (32,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (33,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (83,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (85,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (86,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (87,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (89,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (92,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (95,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (96,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (97,'토핑_추가',0,NULL);
INSERT INTO "MENU_OPT" VALUES (82,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (83,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (84,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (85,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (86,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (87,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (88,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (89,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (90,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (91,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (92,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (93,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (94,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (95,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (96,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (97,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (98,'세트_음료',1,1);
INSERT INTO "MENU_OPT" VALUES (82,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (83,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (84,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (85,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (86,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (87,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (88,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (89,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (90,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (91,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (92,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (93,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (94,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (95,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (96,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (97,'세트_디저트',1,1);
INSERT INTO "MENU_OPT" VALUES (98,'세트_디저트',1,1);
INSERT INTO "MENU_CATEGORY" VALUES (1,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (3,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (4,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (19,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (20,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (21,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (22,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (23,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (24,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (25,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (26,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (27,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (28,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (29,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (30,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (31,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (32,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (33,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (34,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (35,'햄버거');
INSERT INTO "MENU_CATEGORY" VALUES (2,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (82,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (83,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (84,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (85,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (86,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (87,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (88,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (89,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (90,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (91,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (92,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (93,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (94,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (95,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (96,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (97,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (98,'버거세트');
INSERT INTO "MENU_CATEGORY" VALUES (82,'행사메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (83,'행사메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (84,'행사메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (85,'행사메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (86,'행사메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (87,'행사메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (88,'착한점심');
INSERT INTO "MENU_CATEGORY" VALUES (89,'착한점심');
INSERT INTO "MENU_CATEGORY" VALUES (90,'착한점심');
INSERT INTO "MENU_CATEGORY" VALUES (91,'착한점심');
INSERT INTO "MENU_CATEGORY" VALUES (92,'착한점심');
INSERT INTO "MENU_CATEGORY" VALUES (93,'착한점심');
INSERT INTO "MENU_CATEGORY" VALUES (94,'착한점심');
INSERT INTO "MENU_CATEGORY" VALUES (23,'추천메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (19,'추천메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (26,'추천메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (27,'추천메뉴');
INSERT INTO "MENU_CATEGORY" VALUES (5,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (6,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (15,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (16,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (17,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (48,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (49,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (50,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (51,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (52,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (53,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (54,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (55,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (56,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (57,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (58,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (59,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (60,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (61,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (62,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (63,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (64,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (65,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (66,'치킨');
INSERT INTO "MENU_CATEGORY" VALUES (12,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (13,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (14,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (36,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (37,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (38,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (39,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (40,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (41,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (42,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (43,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (44,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (45,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (46,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (47,'디저트');
INSERT INTO "MENU_CATEGORY" VALUES (7,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (8,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (9,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (10,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (67,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (68,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (69,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (70,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (76,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (77,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (78,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (79,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (80,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (81,'음료');
INSERT INTO "MENU_CATEGORY" VALUES (71,'커피');
INSERT INTO "MENU_CATEGORY" VALUES (72,'커피');
INSERT INTO "MENU_CATEGORY" VALUES (73,'커피');
INSERT INTO "MENU_CATEGORY" VALUES (74,'커피');
INSERT INTO "MENU_CATEGORY" VALUES (75,'커피');
INSERT INTO "OPT_PRICE" VALUES (12,'세트_디저트',400);
INSERT INTO "OPT_PRICE" VALUES (13,'세트_디저트',500);
INSERT INTO "OPT_PRICE" VALUES (14,'세트_디저트',200);
INSERT INTO "OPT_PRICE" VALUES (36,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (37,'세트_디저트',0);
INSERT INTO "OPT_PRICE" VALUES (38,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (39,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (40,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (41,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (42,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (43,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (44,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (45,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (46,'세트_디저트',1000);
INSERT INTO "OPT_PRICE" VALUES (47,'세트_디저트',500);
INSERT INTO "OPT_PRICE" VALUES (7,'세트_드링크',0);
INSERT INTO "OPT_PRICE" VALUES (8,'세트_드링크',0);
INSERT INTO "OPT_PRICE" VALUES (9,'세트_드링크',700);
INSERT INTO "OPT_PRICE" VALUES (10,'세트_드링크',700);
INSERT INTO "OPT_PRICE" VALUES (67,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (68,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (69,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (70,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (76,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (77,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (78,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (79,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (80,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (81,'세트_드링크',500);
INSERT INTO "OPT_PRICE" VALUES (71,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (72,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (73,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (74,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (75,'세트_드링크',1000);
INSERT INTO "OPT_PRICE" VALUES (18,'토핑_추가',1200);
INSERT INTO "OPT_PRICE" VALUES (99,'토핑_추가',300);
INSERT INTO "OPT_PRICE" VALUES (100,'토핑_추가',300);
INSERT INTO "OPT_PRICE" VALUES (101,'토핑_추가',500);
INSERT INTO "OPT_PRICE" VALUES (102,'토핑_추가',300);
INSERT INTO "OPT_PRICE" VALUES (15,'치킨팩_소스',0);
INSERT INTO "OPT_PRICE" VALUES (16,'치킨팩_소스',0);
INSERT INTO "OPT_PRICE" VALUES (17,'치킨팩_소스',0);
INSERT INTO "OPT_PRICE" VALUES (62,'치킨팩_소스',0);
INSERT INTO "OPT_PRICE" VALUES (63,'치킨팩_소스',0);
INSERT INTO "OPT_PRICE" VALUES (14,'치킨팩_디저트',0);
INSERT INTO "OPT_PRICE" VALUES (37,'치킨팩_디저트',0);
INSERT INTO "OPT_PRICE" VALUES (15,'추가구매제품',100);
INSERT INTO "OPT_PRICE" VALUES (16,'추가구매제품',100);
INSERT INTO "OPT_PRICE" VALUES (17,'추가구매제품',500);
INSERT INTO "OPT_PRICE" VALUES (50,'추가구매제품',400);
INSERT INTO "OPT_PRICE" VALUES (61,'추가구매제품',500);
INSERT INTO "OPT_PRICE" VALUES (62,'추가구매제품',500);
INSERT INTO "OPT_PRICE" VALUES (63,'추가구매제품',500);
INSERT INTO "OPT_PRICE" VALUES (64,'추가구매제품',200);
INSERT INTO "OPT_PRICE" VALUES (65,'추가구매제품',200);
INSERT INTO "OPT_PRICE" VALUES (66,'추가구매제품',200);
INSERT INTO "INGREDIENT" VALUES (1,'양상추',100.0,'g','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (2,'양파',150.0,'g','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (3,'마요네즈',500.0,'ml',NULL);
INSERT INTO "INGREDIENT" VALUES (4,'불고기버거소스',500.0,'ml',NULL);
INSERT INTO "INGREDIENT" VALUES (5,'새우버거소스',400.0,'ml',NULL);
INSERT INTO "INGREDIENT" VALUES (6,'스위트어섬버거소스',300.0,'ml','');
INSERT INTO "INGREDIENT" VALUES (7,'소고기패티',10.0,'EA','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (8,'새우버거패티',5.0,'EA','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (9,'식물성패티',3.0,'EA','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (10,'햄버거번',10.0,'EA',NULL);
INSERT INTO "INGREDIENT" VALUES (11,'케찹',50.0,'ml',NULL);
INSERT INTO "INGREDIENT" VALUES (12,'머스타드',50.0,'ml',NULL);
INSERT INTO "INGREDIENT" VALUES (13,'데리야끼소스',50.0,'ml',NULL);
INSERT INTO "INGREDIENT" VALUES (14,'브라운소스',50.0,'ml',NULL);
INSERT INTO "INGREDIENT" VALUES (15,'토핑-비프패티',3.0,'EA','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (16,'토핑-슬라이스햄',3.0,'EA','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (17,'토핑-L치즈',3.0,'EA','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (18,'토핑-베이컨',3.0,'EA','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (19,'토핑-토마토',3.0,'EA','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (20,'통닭',2.0,'EA',NULL);
INSERT INTO "INGREDIENT" VALUES (21,'치킨조각',4.0,'EA',NULL);
INSERT INTO "INGREDIENT" VALUES (22,'휠레',6.0,'EA',NULL);
INSERT INTO "INGREDIENT" VALUES (23,'윙',8.0,'EA',NULL);
INSERT INTO "INGREDIENT" VALUES (24,'순살치킨조각',10.0,'EA',NULL);
INSERT INTO "INGREDIENT" VALUES (25,'감자',200.0,'g','https://via.placeholder.com/150');
INSERT INTO "INGREDIENT" VALUES (26,'옥수수',200.0,'g','https://via.placeholder.com/150');



INSERT INTO "MENU" VALUES (4,'새우버거','/static/img/menu/b_srimp.png',3900,'더 커지고, 더 맛있어진 새우 패티로 고유의 맛을 강화한 오리지널 새우버거',0,179.0,492.0,15.0,27.0,810.0,40.0,7.0,4.7,31.0,0.0,NULL);

INSERT INTO "MENU" VALUES (7,'콜라(S,스몰)','/static/img/menu/d_coke.png',1000,'햄버거에 필수 음료 콜라',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "MENU" VALUES (8,'사이다(S,스몰)','/static/img/menu/d_cider.png',1000,'톡톡 쏘는 청량감이 느껴지는 음료',0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "MENU" VALUES (9,'콜라','/static/img/menu/d_coke.png',1700,'햄버거에 필수 음료 콜라',0,420.0,128.0,0.0,1.0,14.0,1.0,31.0,0.0,0.0,0.0,NULL);
INSERT INTO "MENU" VALUES (10,'사이다','/static/img/menu/d_cider.png',1700,'톡톡 쏘는 청량감이 느껴지는 음료',0,420.0,133.0,0.0,1.0,7.0,0.0,31.0,0.0,0.0,0.0,NULL);
INSERT INTO "MENU" VALUES (12,'포테이토L','/static/img/menu/de_potato.png',1900,'신선도 높은 후라잉 오일에 바로 튀겨낸 바삭바삭하고 감칠맛 나는 맛의 후렌치 포테이토',0,130.0,389.0,5.6,10.0,471.0,24.0,0.0,5.0,NULL,NULL,'대두');
INSERT INTO "MENU" VALUES (13,'치즈스틱','/static/img/menu/de_cheezestick_R.png',2000,'치즈에 파슬리를 첨가한 튀김옷을 입혀 바삭바삭하고 부드럽고 고소한 서구풍의 디저트 메뉴',0,49.0,160.0,8.7,16.0,183.0,9.0,0.0,3.0,1.0,0.0,'계란, 밀, 대두, 우유');





INSERT INTO "MENU" VALUES (19,'밀리터리버거','/static/img/menu/b_military.png',5400,'취향대로 조립해 먹는 "군대리아" 컨셉의 KIT타입 버거',0,329.0,813.0,27.0,48.0,1486.0,74.0,33.0,14.0,NULL,0.0,'난류, 밀, 대두, 우유, 토마토, 돼지고기, 조개류(굴), 쇠고기');



INSERT INTO "MENU" VALUES (23,'와규에디션II','/static/img/menu/b_wagu.png',5800,'스테이크 소스로 즐기는 부드럽고 풍부한 맛의 가성비 와규버거',0,185.0,497.0,20.0,36.0,737.0,37.0,14.0,11.4,NULL,0.0,'밀, 대두, 난류, 우유, 토마토, 쇠고기');


INSERT INTO "MENU" VALUES (26,'폴더버거핫치킨','/static/img/menu/b_polder.png',5700,'달콤, 매콤 소스에 핫치킨 토핑을 더한 화끈한 매운맛의 폴더버거',0,218.0,541.0,27.0,49.0,1075.0,54.0,15.0,12.0,NULL,0.0,'밀, 대두, 난류, 우유, 토마토, 쇠고기, 닭고기');
INSERT INTO "MENU" VALUES (27,'리아미라클버거','/static/img/menu/b_miracle.png',5600,'숯불갈비양념맛과 어니언의 풍미가 어우러진 한국적인 맛의 대체육 버거',0,211.0,570.0,19.0,35.0,850.0,43.0,14.0,10.2,NULL,0.0,'밀, 대두 / 동물성 원재료 성분은 포함하지 않습니다. 단, 조리시 교차 혼입의 가능성이 있습니다.');


INSERT INTO "MENU" VALUES (30,'클래식치즈버거','/static/img/menu/b_clasic.png',4400,'부드럽고 촉촉한 포테이토번과 풍부한 육즙의 두툼한 호주산 쇠고기패티로 본연의 맛을 꽉 채운 클래식 치즈버거',0,143.0,483.0,20.0,20.0,672.0,34.0,6.0,16.0,NULL,0.0,'밀, 대두, 난류, 우유, 쇠고기');
INSERT INTO "MENU" VALUES (31,'T.REX(티렉스)','/static/img/menu/b_trax.png',4700,'빅사이즈 통다리살 치킨패티의 쥬시함과 부드럽고 달콤상큼한 소스 맛이 조화로운 제품',0,213.0,475.0,26.2,48.0,874.0,44.0,7.0,5.0,48.0,0.0,'밀, 대두, 난류, 우유, 닭고기, 땅콩');
INSERT INTO "MENU" VALUES (32,'치킨버거','/static/img/menu/b_chicken.png',2900,'쫄깃한 닭다리 살 패티로 만든 육즙과 풍미가 뛰어난 고단백 치킨버거',0,141.0,355.0,15.0,28.0,619.0,31.0,8.0,3.8,NULL,0.0,'밀, 대두, 난류, 우유, 닭고기, 땅콩, 조개류');




INSERT INTO "MENU" VALUES (37,'포테이토','/static/img/menu/de_potato.png',1500,'신선도 높은 후라잉 오일에 바로 튀겨낸 바삭바삭하고 감칠맛 나는 맛의 후렌치 포테이토',0,90.0,292.0,2.9,5.0,268.0,13.0,0.0,4.0,0.0,0.0,'대두');
INSERT INTO "MENU" VALUES (38,'양념감자','/static/img/menu/de_potato_s.png',2000,'고객의 기호에 맞게 시즈닝(오니언, 치즈, 칠리)을 한가지를 선택해서 직접 뿌려먹는 포테이토',0,121.0,365.0,5.5,10.0,542.0,27.0,2.0,4.0,11.0,0.0,'어니언, 치즈: 대두, 우유 / 칠리: 밀, 대두, 우유, 토마토, 쇠고기');
INSERT INTO "MENU" VALUES (39,'롱치즈스틱','/static/img/menu/de_cheezestick.png',1800,'기존 치즈스틱보다 길어진 모짜렐라치즈 물성의 특징인 늘어남과 고소한 풍미를 활용한 디저트 메뉴',0,49.0,156.0,7.8,14.0,236.0,12.0,0.0,7.0,3.0,0.0,'계란, 밀, 대두, 우유');

INSERT INTO "MENU" VALUES (41,'쉑쉑치킨','/static/img/menu/de_sheck.png',2500,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO "MENU" VALUES (43,'토네이도-쵸코쿠키','/static/img/menu/de_to_choco.png',2100,'부드러운 아이스크림에 달콤하고 깔끔한 초코쿠키를 넣어 어린 아이부터 주부에 이르기까지 보는 즐거움과 먹는 즐거움을 함께하는 아이스크림',0,175.0,308.0,4.5,8.0,122.0,6.0,27.0,10.0,180.0,0.0,'밀, 대두, 우유');

INSERT INTO "MENU" VALUES (45,'토네이도-스토로베리','/static/img/menu/de_to_berry.png',3400,'딸기의 새콤달콤한 맛과 스트로베리 후레이크의 아삭 아삭한 맛이 좋아 천연 과일을 선호하는 고객을 위한 제품으로 보는 즐거움과 먹는 즐거움을 함께하는 아이스크림',0,177.0,272.0,3.5,6.0,54.0,3.0,29.0,8.0,196.0,0.0,'우유');


INSERT INTO "MENU" VALUES (103,'새우버거(세트)','https://via.placeholder.com/150',5900,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "MENU" VALUES (104,'치킨버거(세트)','https://via.placeholder.com/150',4900,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "MENU" VALUES (85,'리아미라클버거(세트)','https://via.placeholder.com/150',5500,'숯불갈비양념맛과 어니언의 풍미가 어우러진 한국적인 맛의 대체육 버거',0,720.0,965.0,23.0,42.0,1187.0,59.0,45.0,13.0,NULL,NULL,'밀, 대두 / 동물성 원재료 성분은 포함하지 않습니다. 단, 조리시 교차 혼입의 가능성이 있습니다.');



















INSERT INTO "MENU" VALUES (68,'아이스티L','/static/img/menu/d_icetea.png',2500,'달콤한 복숭아 맛의 시원한 대용량 아이스 드링크',0,467.0,232.0,0.0,0.0,0.0,0.0,56.0,0.0,0.0,0.0,'복숭아');
INSERT INTO "MENU" VALUES (69,'콜라(L,라지)','/static/img/menu/d_coke.png',1900,'톡톡 쏘는 청량감이 느껴지는 음료',0,570.0,174.0,0.4,1.0,20.0,1.0,42.0,0.0,282.0,0.0,'-');
INSERT INTO "MENU" VALUES (70,'사이다(L,라지)','/static/img/menu/d_cider.png',1900,'톡톡 쏘는 청량감이 느껴지는 음료',0,570.0,182.0,0.4,1.0,9.0,0.0,42.0,0.0,281.0,0.0,'-');
INSERT INTO "MENU" VALUES (71,'아메리카노','/static/img/menu/d_ame.png',2000,'에스프레소 커피를 물로 희석하여 커피의 풍부한 맛을 살린 제품(고카페인 함유) *어린이, 임산부, 카페인 민감자는 섭취에 주의 바랍니다.',0,270.0,23.0,0.7,1.0,1.0,0.0,0.0,0.0,0.0,NULL,'-');
INSERT INTO "MENU" VALUES (72,'아이스아메리카노','/static/img/menu/d_iceame_R.png',2000,'차갑게 즐기는 맛이 풍부한 에스프레소 커피 (고카페인 함유) *어린이, 임산부, 카페인 민감자는 섭취에 주의 바랍니다.',0,310.0,32.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,NULL,'-');
INSERT INTO "MENU" VALUES (73,'아이스아메리카노(L,라지)','/static/img/menu/d_iceame_R.png',2500,'에스프레소 커피를 물로 희석하여 커피의 풍부한 맛을 살린 제품(고카페인 함유) *어린이, 임산부, 카페인 민감자는 섭취에 주의 바랍니다.',0,530.0,50.0,2.0,4.0,3.0,0.0,0.0,1.0,0.0,NULL,'-');



INSERT INTO "MENU" VALUES (77,'우유','/static/img/menu/d_milk.png',1500,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO "MENU" VALUES (79,'오렌지주스(PET)','/static/img/menu/d_oragej.png',2500,'',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "MENU" VALUES (80,'아이스티','/static/img/menu/d_icetea.png',2200,'달콤한 복숭아 맛의 시원한 아이스 드링크',0,310.0,160.0,0.0,0.0,0.0,0.0,39.0,0.0,NULL,0.0,'복숭아');
INSERT INTO "MANAGER" VALUES (1, 'admin', '1234', '홍길동', '매니저'); 























COMMIT;
