BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "MENU" (
	"ID"	INTEGER,
	"NAME"	TEXT UNIQUE,
	"IMG"	BLOB,
	"PRICE"	INTEGER,
	"DESC"	TEXT,
	"CATEGORY"	TEXT,
	"IS_SOLDOUT"	INTEGER,
	"IS_PROMO"	INTEGER,
	"WEIGHT_G"	REAL,
	"KCAL"	REAL,
	"PROTEIN_G"	REAL,
	"PROTEIN_PCENT"	REAL,
	"SODIUM_MG"	REAL,
	"SODIUM_PCENT"	REAL,
	"SUGAR_G"	REAL,
	"SAT_FAT"	REAL,
	"SAT_FAT_PCENT"	REAL,
	"CAFFEINE_MG"	REAL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "INGRD_USE" (
	"MENU_ID"	INTEGER,
	"INGRD_ID"	INTEGER,
	"AMT"	REAL,
	FOREIGN KEY("MENU_ID") REFERENCES "MENU"("ID"),
	FOREIGN KEY("INGRD_ID") REFERENCES "INGREDIENT"("ID"),
	PRIMARY KEY("MENU_ID","INGRD_ID")
);
CREATE TABLE IF NOT EXISTS "ALLERGY_INFO" (
	"MENU_ID"	INTEGER,
	"SUBSTANCE"	TEXT,
	FOREIGN KEY("MENU_ID") REFERENCES "MENU"("ID"),
	PRIMARY KEY("MENU_ID")
);
CREATE TABLE IF NOT EXISTS "MENU_OPT" (
	"MENU_ID"	INTEGER,
	"OPT_TAG"	TEXT,
	"QTY_MIN"	INTEGER,
	"QTY_MAX"	INTEGER,
	FOREIGN KEY("MENU_ID") REFERENCES "MENU"("ID"),
	PRIMARY KEY("MENU_ID","OPT_TAG")
);
CREATE TABLE IF NOT EXISTS "OPT_PRICE" (
	"MENU_ID"	INTEGER,
	"OPT_TAG"	TEXT,
	"OPT_PRICE"	INTEGER,
	FOREIGN KEY("MENU_ID") REFERENCES "MENU"("ID"),
	PRIMARY KEY("MENU_ID","OPT_TAG")
);
CREATE TABLE IF NOT EXISTS "ORDER_ITEM" (
	"ORDER_ID"	INTEGER,
	"ITEM_NO"	INTEGER,
	"MAIN_DISH_ID"	INTEGER,
	"QTY"	INTEGER,
	"MAIN_DISH_TOTAL"	INTEGER,
	FOREIGN KEY("ORDER_ID") REFERENCES "ORDER"("ID"),
	FOREIGN KEY("MAIN_DISH_ID") REFERENCES "MENU"("ID"),
	PRIMARY KEY("ORDER_ID","ITEM_NO")
);
CREATE TABLE IF NOT EXISTS "OPT_CHOICE" (
	"ORDER_ID"	INTEGER,
	"ITEM_NO"	INTEGER,
	"OPTION_ID"	INTEGER,
	"OPT_QTY"	INTEGER,
	"OPT_TOTAL"	INTEGER,
	FOREIGN KEY("OPTION_ID") REFERENCES "MENU"("ID"),
	FOREIGN KEY("ORDER_ID") REFERENCES "ORDER"("ID"),
	FOREIGN KEY("ITEM_NO") REFERENCES "ORDER_ITEM"("ITEM_NO"),
	PRIMARY KEY("ORDER_ID","OPTION_ID","ITEM_NO")
);
CREATE TABLE IF NOT EXISTS "MANAGER" (
	"ID"	INTEGER,
	"LOGIN_ID"	TEXT UNIQUE,
	"LOGIN_PWD"	TEXT,
	"NAME"	TEXT,
	"POSITION"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "ORDER" (
	"ID"	INTEGER,
	"WAIT_NO"	INTEGER,
	"STATUS"	TEXT,
	"ORDERED_AT"	timestamp,
	"SERVED_AT"	timestamp,
	"CANCELLED_AT"	timestamp,
	"RECEIPT_TOTAL"	INTEGER,
	"IS_TOGO"	INTEGER,
	"PAY_METHOD"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "INGREDIENT" (
	"ID"	INTEGER,
	"NAME"	TEXT UNIQUE,
	"STOCK"	REAL,
	"UNIT"	TEXT,
	PRIMARY KEY("ID")
);
COMMIT;
